baseURL = "https://foundation.graphql.org"
languageCode = "en-us"
title = "The GraphQL Foundation"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTxt = true

[params]
tagline = "An open and neutral home for the GraphQL community"
description = "An open and neutral home for the GraphQL community dedicated to promoting widespread adoption and accelerating development of the surrounding ecosystem"
copyright = "All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](http://www.linuxfoundation.org/privacy) and [Terms of Use](http://www.linuxfoundation.org/terms)."

[params.logos]
hero   = "graphql-foundation.png"
navbar = "graphql-foundation.png"
footer = "graphql-icon.svg"
topper = "lf-projects.png"

[permalinks]
news = "/news/:year/:month/:day/:title"

[[menu.nav]]
name = "About"
identifier = "about"
weight = 1

[[menu.nav]]
name = "Charter"
parent = "about"
url = "https://github.com/graphql/foundation/blob/master/CODE-OF-CONDUCT.md"
weight = 1

[[menu.nav]]
name = "FAQ"
parent = "about"
url = "/faq"
weight = 2

[[menu.nav]]
name = "Code of Conduct"
parent = "about"
url = "https://github.com/graphql/foundation/blob/master/CODE-OF-CONDUCT.md"
weight = 3

[[menu.nav]]
name = "Contact"
parent = "about"
url = "/contact"
weight = 4

[[menu.nav]]
name = "Landscape"
url = "https://landscape.graphql.org"
weight = 2

[[menu.nav]]
name = "News"
identifier = "news"
weight = 3

[[menu.nav]]
name = "All News"
parent = "news"
url = "/news"
weight = 1

[[menu.nav]]
name = "Announcements"
parent = "news"
url = "/news/announcements"
weight = 2

[[menu.nav]]
name = "In the News"
parent = "news"
url = "/news/in-the-news"
weight = 3

[[menu.nav]]
name = "GraphQL Newsletter"
parent = "news"
url = "/news/graphql-newsletter"
weight = 4

[[menu.nav]]
name = "Projects"
url = "/projects"
weight = 4

[[menu.nav]]
name = "Members"
identifier = "members"
weight = 5

[[menu.nav]]
name = "Our Members"
parent = "members"
url = "/members"
weight = 1

[[menu.nav]]
name = "Join"
parent = "members"
url = "/join"
weight = 2

[[menu.nav]]
name = "Annual Reports"
identifier = "reports"
weight = 6

[[menu.nav]]
name = "2019 Annual Report"
parent = "reports"
url = "/reports/annual-report-2019"
weight = 1
